# Generated by Django 4.2.30 on 2026-08-16 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('style', models.CharField(max_length=80)),
                ('glb_url', models.CharField(help_text='Public URL path to the .glb, e.g. /models/modern-family.glb', max_length=255)),
                ('recommended_min_plot', models.FloatField(help_text='Inclusive minimum plot size in m²')),
                ('recommended_max_plot', models.FloatField(help_text='Inclusive maximum plot size in m²')),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('floors', models.PositiveSmallIntegerField()),
                ('parking', models.BooleanField(default=False)),
                ('estimated_cost_pkr', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['recommended_min_plot'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_size_sqm', models.FloatField()),
                ('land_size_display_unit', models.CharField(default='marla', max_length=16)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('plot_points', models.JSONField(blank=True, default=list, help_text='Hit-test corners as [{x,y,z}, ...] in metres')),
                ('recommendation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='planning.housedesign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration_text', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='huggingface', max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='planning.project')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
