# Generated by Django 4.2.30 on 2026-09-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_enrich_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housedesign',
            options={'ordering': ['style', 'recommended_min_plot', 'name']},
        ),
        migrations.AddField(
            model_name='housedesign',
            name='attribution_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='balconies',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='building_depth_m',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='building_footprint_sqm',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='building_height_m',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='building_width_m',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='commercial_use_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='currency',
            field=models.CharField(default='PKR', max_length=8),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='dining_rooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='estimated_cost_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='estimated_cost_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='family_rooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='garden',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='kitchens',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='living_rooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='max_plot_area_sqm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='min_plot_area_sqm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='model_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='model_depth_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='model_height_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='model_type',
            field=models.CharField(choices=[('procedural', 'Procedural Three.js'), ('glb', 'Local / hosted GLB')], default='procedural', max_length=16),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='model_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='model_width_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='parking_spaces',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='recommended_depth_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='recommended_width_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='source_attribution',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='source_license',
            field=models.CharField(default='project-generated', max_length=120),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='source_model_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='source_provider',
            field=models.CharField(default='plotline-procedural', max_length=80),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='terraces',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='feasibility_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='preferred_style',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='housedesign',
            name='glb_url',
            field=models.CharField(blank=True, default='', help_text='Used when model_type=glb', max_length=255),
        ),
        migrations.AlterField(
            model_name='housedesign',
            name='style',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
