# Generated by Django 4.2.30 on 2026-09-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_enrich_house_design_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedesign',
            name='dirty_kitchens',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='drawing_rooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='parking_spaces_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='powder_rooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='room_sizes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='housedesign',
            name='study_rooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
