# Generated by Django 4.2 for AI camera measurement metadata

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0004_planning_room_cost_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="calibration_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. user_reference | none",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="measurement_quality",
            field=models.CharField(
                blank=True,
                choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                default="",
                help_text="HIGH | MEDIUM | LOW for AI camera; blank for manual/AR",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="measurement_type",
            field=models.CharField(
                choices=[
                    ("ar", "AR hit-test / WebXR"),
                    ("manual", "Manual rectangle"),
                    ("ai_camera", "AI camera measurement"),
                ],
                default="manual",
                max_length=16,
            ),
        ),
    ]
