"""Catalog styles and procedural HouseDesign seed rows."""
from django.core.management.base import BaseCommand

from planning.models import HouseDesign

STYLES = {
    "Modern": "Clean geometric volumes, flat roofs, large glazing, minimal exterior.",
    "Italian Villa": "Warm stucco, columns, arched openings, terracotta roof, villa proportions.",
    "American": "Wider frontage, garage emphasis, pitched roof, family porch.",
    "Cottage / Hut": "Compact footprint, pitched roof, warm materials, garden cottage feel.",
    "Contemporary": "Asymmetrical volumes, mixed materials, large glass, modern landscaping.",
    "Traditional": "Balanced facade, conventional windows, porch entry, pitched roof.",
    "Luxury Villa": "Multi-volume premium facade, terraces, pool when plot allows, architectural lighting.",
}


def _cfg(style_key, floors, width, depth, features):
    return {
        "style": style_key,
        "floors": floors,
        "footprint": {"width": width, "depth": depth},
        "features": features,
    }


def _row(**kwargs):
    w = kwargs["building_width_m"]
    d = kwargs["building_depth_m"]
    kwargs.setdefault("building_footprint_sqm", round(w * d, 1))
    kwargs.setdefault("min_plot_area_sqm", kwargs["recommended_min_plot"])
    kwargs.setdefault("max_plot_area_sqm", kwargs["recommended_max_plot"])
    kwargs.setdefault("model_type", HouseDesign.MODEL_PROCEDURAL)
    kwargs.setdefault("source_provider", "plotline-procedural")
    kwargs.setdefault("source_license", "project-generated")
    kwargs.setdefault("currency", "PKR")
    kwargs.setdefault("active", True)
    kwargs.setdefault("parking", kwargs.get("parking_spaces", 0) > 0)
    kwargs.setdefault("glb_url", "")
    return kwargs


DESIGNS = [
    # Modern
    _row(
        name="Modern Compact",
        style="Modern",
        description="Single-storey modern pavilion with large glass and flat roof.",
        recommended_min_plot=70,
        recommended_max_plot=120,
        building_width_m=9,
        building_depth_m=8,
        building_height_m=4.2,
        floors=1,
        bedrooms=2,
        bathrooms=2,
        living_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=1,
        balconies=0,
        terraces=1,
        garden=True,
        estimated_cost_pkr=8_500_000,
        estimated_cost_min=7_000_000,
        estimated_cost_max=10_000_000,
        model_config=_cfg(
            "modern",
            1,
            9,
            8,
            {"balcony": False, "garage": False, "pool": False, "terrace": True, "cantilever": True},
        ),
    ),
    _row(
        name="Modern Family",
        style="Modern",
        description="Two-storey modern home with cantilevered upper volume and courtyard glazing.",
        recommended_min_plot=140,
        recommended_max_plot=220,
        building_width_m=11,
        building_depth_m=10,
        building_height_m=7.5,
        floors=2,
        bedrooms=3,
        bathrooms=3,
        living_rooms=1,
        family_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=1,
        balconies=2,
        terraces=1,
        garage=True,
        garden=True,
        estimated_cost_pkr=18_000_000,
        estimated_cost_min=15_000_000,
        estimated_cost_max=22_000_000,
        model_config=_cfg(
            "modern",
            2,
            11,
            10,
            {"balcony": True, "garage": True, "pool": False, "terrace": True, "cantilever": True},
        ),
    ),
    _row(
        name="Modern Large",
        style="Modern",
        description="Layered modern villa volumes with terrace and optional pool deck.",
        recommended_min_plot=220,
        recommended_max_plot=360,
        building_width_m=14,
        building_depth_m=12,
        building_height_m=8.5,
        floors=2,
        bedrooms=4,
        bathrooms=4,
        living_rooms=1,
        family_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=2,
        balconies=3,
        terraces=2,
        garage=True,
        pool=True,
        garden=True,
        estimated_cost_pkr=32_000_000,
        estimated_cost_min=28_000_000,
        estimated_cost_max=38_000_000,
        model_config=_cfg(
            "modern",
            2,
            14,
            12,
            {"balcony": True, "garage": True, "pool": True, "terrace": True, "cantilever": True},
        ),
    ),
    # Italian
    _row(
        name="Italian Compact Villa",
        style="Italian Villa",
        description="Compact Mediterranean villa with stucco, tile roof, and entry columns.",
        recommended_min_plot=120,
        recommended_max_plot=180,
        building_width_m=10,
        building_depth_m=9,
        building_height_m=7.0,
        floors=2,
        bedrooms=3,
        bathrooms=2,
        living_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=1,
        balconies=2,
        terraces=1,
        garden=True,
        estimated_cost_pkr=16_000_000,
        estimated_cost_min=14_000_000,
        estimated_cost_max=19_000_000,
        model_config=_cfg(
            "italian",
            2,
            10,
            9,
            {"balcony": True, "garage": False, "pool": False, "terrace": True, "columns": True, "arches": True},
        ),
    ),
    _row(
        name="Italian Family Villa",
        style="Italian Villa",
        description="Symmetrical Italianate villa with portico, arched openings, and terracotta roof.",
        recommended_min_plot=160,
        recommended_max_plot=260,
        building_width_m=12,
        building_depth_m=11,
        building_height_m=8.5,
        floors=2,
        bedrooms=3,
        bathrooms=3,
        living_rooms=1,
        family_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=1,
        balconies=3,
        terraces=1,
        garden=True,
        estimated_cost_pkr=24_000_000,
        estimated_cost_min=20_000_000,
        estimated_cost_max=28_000_000,
        model_config=_cfg(
            "italian",
            2,
            12,
            11,
            {"balcony": True, "garage": True, "pool": False, "terrace": True, "columns": True, "arches": True},
        ),
    ),
    _row(
        name="Italian Large Villa",
        style="Italian Villa",
        description="Grand villa massing with pediment portico, bay windows, and landscaped court.",
        recommended_min_plot=260,
        recommended_max_plot=420,
        building_width_m=16,
        building_depth_m=13,
        building_height_m=9.5,
        floors=2,
        bedrooms=5,
        bathrooms=4,
        living_rooms=1,
        family_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=2,
        balconies=4,
        terraces=2,
        garage=True,
        pool=True,
        garden=True,
        estimated_cost_pkr=45_000_000,
        estimated_cost_min=40_000_000,
        estimated_cost_max=55_000_000,
        model_config=_cfg(
            "italian",
            2,
            16,
            13,
            {"balcony": True, "garage": True, "pool": True, "terrace": True, "columns": True, "arches": True},
        ),
    ),
    # American
    _row(
        name="American Family",
        style="American",
        description="Practical family home with front porch, driveway garage, and pitched roof.",
        recommended_min_plot=150,
        recommended_max_plot=240,
        building_width_m=13,
        building_depth_m=10,
        building_height_m=7.8,
        floors=2,
        bedrooms=3,
        bathrooms=2,
        living_rooms=1,
        family_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=2,
        balconies=0,
        terraces=0,
        garage=True,
        garden=True,
        estimated_cost_pkr=20_000_000,
        estimated_cost_min=17_000_000,
        estimated_cost_max=24_000_000,
        model_config=_cfg(
            "american",
            2,
            13,
            10,
            {"balcony": False, "garage": True, "pool": False, "terrace": False, "porch": True},
        ),
    ),
    _row(
        name="American Large",
        style="American",
        description="Wider frontage American home with double garage and upper dormers.",
        recommended_min_plot=240,
        recommended_max_plot=380,
        building_width_m=16,
        building_depth_m=12,
        building_height_m=8.5,
        floors=2,
        bedrooms=4,
        bathrooms=3,
        living_rooms=1,
        family_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=2,
        balconies=1,
        terraces=1,
        garage=True,
        garden=True,
        estimated_cost_pkr=30_000_000,
        estimated_cost_min=26_000_000,
        estimated_cost_max=36_000_000,
        model_config=_cfg(
            "american",
            2,
            16,
            12,
            {"balcony": True, "garage": True, "pool": False, "terrace": True, "porch": True},
        ),
    ),
    # Cottage
    _row(
        name="Cottage Compact",
        style="Cottage / Hut",
        description="Warm compact cottage with pitched roof, porch, and garden setting.",
        recommended_min_plot=50,
        recommended_max_plot=110,
        building_width_m=8,
        building_depth_m=7,
        building_height_m=5.0,
        floors=1,
        bedrooms=2,
        bathrooms=1,
        living_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=0,
        balconies=0,
        terraces=0,
        garden=True,
        estimated_cost_pkr=6_500_000,
        estimated_cost_min=5_500_000,
        estimated_cost_max=8_000_000,
        model_config=_cfg(
            "cottage",
            1,
            8,
            7,
            {"balcony": False, "garage": False, "pool": False, "terrace": False, "porch": True},
        ),
    ),
    _row(
        name="Cottage Family",
        style="Cottage / Hut",
        description="Two-storey cottage with timber accents and covered entry porch.",
        recommended_min_plot=110,
        recommended_max_plot=180,
        building_width_m=10,
        building_depth_m=9,
        building_height_m=7.0,
        floors=2,
        bedrooms=3,
        bathrooms=2,
        living_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=1,
        balconies=1,
        terraces=0,
        garden=True,
        estimated_cost_pkr=12_000_000,
        estimated_cost_min=10_000_000,
        estimated_cost_max=14_000_000,
        model_config=_cfg(
            "cottage",
            2,
            10,
            9,
            {"balcony": True, "garage": False, "pool": False, "terrace": False, "porch": True},
        ),
    ),
    # Contemporary
    _row(
        name="Contemporary Family",
        style="Contemporary",
        description="Asymmetrical contemporary volumes with stone accents and large glass.",
        recommended_min_plot=150,
        recommended_max_plot=240,
        building_width_m=12,
        building_depth_m=10,
        building_height_m=8.0,
        floors=2,
        bedrooms=3,
        bathrooms=3,
        living_rooms=1,
        family_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=1,
        balconies=2,
        terraces=1,
        garage=True,
        garden=True,
        estimated_cost_pkr=22_000_000,
        estimated_cost_min=19_000_000,
        estimated_cost_max=26_000_000,
        model_config=_cfg(
            "contemporary",
            2,
            12,
            10,
            {"balcony": True, "garage": True, "pool": False, "terrace": True, "cantilever": True},
        ),
    ),
    _row(
        name="Contemporary Large",
        style="Contemporary",
        description="Larger contemporary residence with terrace wing and landscaped court.",
        recommended_min_plot=240,
        recommended_max_plot=380,
        building_width_m=15,
        building_depth_m=12,
        building_height_m=9.0,
        floors=2,
        bedrooms=4,
        bathrooms=4,
        living_rooms=1,
        family_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=2,
        balconies=3,
        terraces=2,
        garage=True,
        pool=True,
        garden=True,
        estimated_cost_pkr=35_000_000,
        estimated_cost_min=30_000_000,
        estimated_cost_max=42_000_000,
        model_config=_cfg(
            "contemporary",
            2,
            15,
            12,
            {"balcony": True, "garage": True, "pool": True, "terrace": True, "cantilever": True},
        ),
    ),
    # Traditional
    _row(
        name="Traditional Family",
        style="Traditional",
        description="Balanced traditional facade with porch columns and pitched roof.",
        recommended_min_plot=140,
        recommended_max_plot=240,
        building_width_m=12,
        building_depth_m=10,
        building_height_m=8.0,
        floors=2,
        bedrooms=3,
        bathrooms=2,
        living_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=1,
        balconies=1,
        terraces=0,
        garden=True,
        estimated_cost_pkr=17_000_000,
        estimated_cost_min=14_000_000,
        estimated_cost_max=20_000_000,
        model_config=_cfg(
            "traditional",
            2,
            12,
            10,
            {"balcony": True, "garage": False, "pool": False, "terrace": False, "porch": True, "columns": True},
        ),
    ),
    # Luxury
    _row(
        name="Luxury Villa Large",
        style="Luxury Villa",
        description="Premium multi-volume villa with terrace, glass facade, and landscaped approach.",
        recommended_min_plot=280,
        recommended_max_plot=450,
        building_width_m=18,
        building_depth_m=14,
        building_height_m=9.5,
        floors=2,
        bedrooms=5,
        bathrooms=5,
        living_rooms=2,
        family_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=2,
        balconies=4,
        terraces=2,
        garage=True,
        pool=True,
        garden=True,
        estimated_cost_pkr=55_000_000,
        estimated_cost_min=48_000_000,
        estimated_cost_max=70_000_000,
        model_config=_cfg(
            "luxury",
            2,
            18,
            14,
            {"balcony": True, "garage": True, "pool": True, "terrace": True, "cantilever": True, "lighting": True},
        ),
    ),
    _row(
        name="Luxury Villa Premium",
        style="Luxury Villa",
        description="Largest luxury programme with pool deck, wing volumes, and evening facade lighting.",
        recommended_min_plot=420,
        recommended_max_plot=700,
        building_width_m=22,
        building_depth_m=16,
        building_height_m=10.5,
        floors=2,
        bedrooms=6,
        bathrooms=6,
        living_rooms=2,
        family_rooms=1,
        dining_rooms=1,
        kitchens=1,
        parking_spaces=3,
        balconies=5,
        terraces=3,
        garage=True,
        pool=True,
        garden=True,
        estimated_cost_pkr=85_000_000,
        estimated_cost_min=75_000_000,
        estimated_cost_max=110_000_000,
        model_config=_cfg(
            "luxury",
            2,
            22,
            16,
            {"balcony": True, "garage": True, "pool": True, "terrace": True, "cantilever": True, "lighting": True},
        ),
    ),
]


class Command(BaseCommand):
    help = "Seed architectural style catalog (procedural Three.js designs)."

    def handle(self, *args, **options):
        # Deactivate legacy thin catalog names that conflict with new naming
        legacy = [
            "Compact Cottage",
            "Modern Family Home",
            "Contemporary Villa",
            "Italian Villa",
        ]
        HouseDesign.objects.filter(name__in=legacy).update(active=False)

        for row in DESIGNS:
            obj, created = HouseDesign.objects.update_or_create(
                name=row["name"], defaults=row
            )
            self.stdout.write(("Created" if created else "Updated") + ": " + obj.name)

        self.stdout.write(self.style.SUCCESS("Styles: " + ", ".join(STYLES.keys())))
        self.stdout.write(self.style.SUCCESS("Active designs: {}".format(
            HouseDesign.objects.filter(active=True).count()
        )))
